engines:
  csslint:
    enabled: true
  phpcodesniffer:
  	enabled: true
  phpmd:
  	enabled:true

exclude_paths:
  - "assets/*"
  - "sample-config.php"
  - "kirki-user-tests.php"
  - "tests/*"
  - "bin/*"
