---
engines:
  csslint:
    enabled: true
    checks:
      fallback-colors:
        enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseMethodName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- controls/sortable/serialize.js
- controls/**/selectize.js
- assets/js/vendor/*
- tests/*
- bin/*
