language: php

sudo: false

notifications:
  on_success: never
  on_failure: change

php:
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_install:
  - pip install --user codecov

before_script:
	- travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - find . \( -name '*kirki*.php' \) -exec php -lf {} \;

after_script:
  - php vendor/bin/coveralls -v

after_success:
	- codecov
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
