language: php

sudo: false

notifications:
  on_success: never
  on_failure: change

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - mkdir -p build/logs
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls
