# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kirki Documentation
email: aristath@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Kirki WordPress Customizer plugin.
baseurl: "/kirki" # the subpath of your site, e.g. /blog
url: "https://aristath.github.io/kirki/" # the base hostname & protocol for your site
twitter_username: aristath
github_username:  aristath

# Build settings
markdown: kramdown
